version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'WH_docker'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sboomi'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sboomi'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root2020'
      MYSQL_HOST: '0.0.0.0:3306'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_vol:/var/lib/mysql
# Names our volume
volumes:
  mysql_vol: